server:
  port: 8090

spring:
  application:
    name: demo-library

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/demo_library
    type: com.zaxxer.hikari.HikariDataSource